engines:
  php:
    enabled: true
    config:
      auto_discovery: true
      metrics: all
      analyze_paths:
        - src/
        - tests/
exclude_patterns:
  - vendor/
  - node_modules/
  - .git/
